### ISSUE TITLE
Wrong number of arguments for format string

### ISSUE THREAD

**Issue by dploeger** [dploeger/zimbra.de_dieploegers_groupcal#1]
[Here](https://github.com/dploeger/zimbra.de_dieploegers_groupcal/blob/master/agent/groupcal.py#L347) two  arguments are needed while only one is supplied. The problem is, that because of this non-development-savvy users don't get a proper message shown, when the domain only needs a preauth key.

**Comment by ghost** [comment]
Basically in some cases groupcal requires a preauth key to be available on the domain, adding it to the automated installer, and made a comment on that the readme
