### ISSUE TITLE
sometime will show error 

### ISSUE THREAD

**Issue by ztjevan** [dploeger/zimbra.de_dieploegers_groupcal#10]
When user  using this zimlet, some of them will get the error "System error. Could not fetch timespan." and then blank.
![20181101101032](https://user-images.githubusercontent.com/10355631/47828625-da40ba80-ddbe-11e8-877b-b0f24b8c4a97.png)
![20181101101156](https://user-images.githubusercontent.com/10355631/47828626-dad95100-ddbe-11e8-9576-404ff1813540.png)
some times they logout and login again or refresh the brower, the system will ok again.  but some time it still blank.
some times some of them will get calander display, but no data in it. you need to logout and login. 
![20181101101314](https://user-images.githubusercontent.com/10355631/47828627-dad95100-ddbe-11e8-9337-669314005247.png)

**Comment by ghost** [comment]
No timespan, means there is no data available.

Which means, either no-one has any appointment, or in old version, sqlite was locked.

Retry installing the latest version.

**Comment by ghost** [comment]
see also: https://github.com/Zimbra-Community/group-calendar/issues/12
