### ISSUE TITLE
Zimlet won't display in GUI

### ISSUE THREAD

**Issue by davethemacguy** [dploeger/zimbra.de_dieploegers_groupcal#11]
I've followed the guide. I think I have everything in place. Yet when a user logs in, they do not see the Group Calendar tab. What should I be looking at? The zimlet appears to have deployed correctly.

**Comment by ghost** [comment]
I know, see the readme, I just updated.

**Comment by ghost** [comment]
Only users that are in sec_gcal_....@domain.com see the Zimlet.

We have done some maintenance on this project, so you can try the installer on a test server and see if that works.
