### ISSUE TITLE
Feature request-Access Management

### ISSUE THREAD

**Issue by AzizOuedraogo88** [dploeger/zimbra.de_dieploegers_groupcal#3]
Hi Barry,

Thank you again for this very useful Zimlet.

I am looking to do the same thing but with the access management on the others calendar.  (i want to be able for exemple to add  an appointment to the calendar of one of my colleague or to modify it)

Do you think that it can be a new feature?

Thanks

**Comment by ghost** [comment]
Hi AzizOuedraogo88,

I will probably not add features to this Zimlet in the near future, but what you want, can be done with the build in sharing options of Zimbra.

You can also copy-paste this script and run it from your server:
https://gist.github.com/barrydegraaff/48e68ab9d4f97536446b

Call the script subzim (chmod +rx) and then use:
subzim <primary account needing access to> <this secondary account>

This will share entire mailbox, not only calendar. But you can do that via GUI as well.
