### ISSUE TITLE
Various installation problems

### ISSUE THREAD

**Issue by Deelight-fr** [dploeger/zimbra.de_dieploegers_groupcal#4]
I'm trying to install groupcal on Version 8.6.0_GA_1182.NETWORK.

Following the installation instructions, I get an error when I run (on a store) : 
zmzimletctl deploy de_dieploegers_groupcal.zip

> [] INFO: Deploying Zimlet de_dieploegers_groupcal in LDAP.
> [] INFO: Installing Zimlet de_dieploegers_groupcal on this host.
> [] INFO: Upgrading Zimlet de_dieploegers_groupcal to 1.0
> [] INFO: Installing Zimlet config for de_dieploegers_groupcal
> [] INFO: Adding Zimlet de_dieploegers_groupcal to COS default
> [] INFO: Enabling Zimlet de_dieploegers_groupcal
> [] INFO: Deploying on ui node zldap.mydomain.tld
> [] INFO: deploy failed on ui node zldap.mydomain.tld
> com.zimbra.common.service.ServiceException: invalid request: server zldap.mydomain.tld does not have zimbraMailMode set, maybe it is not a store server?
> ExceptionId:main:1474372108997:83a53ef484c68f16
> Code:service.INVALID_REQUEST
> at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:267)
> at com.zimbra.cs.httpclient.URLUtil.getServiceURL(URLUtil.java:186)
> at com.zimbra.cs.util.WebClientServiceUtil.sendDeployZimletRequestToUiNode(WebClientServiceUtil.java:260)
> at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletOnUiNode(ZimletUtil.java:1567)
> at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletRemotely(ZimletUtil.java:1477)
> at com.zimbra.cs.zimlet.ZimletUtil.deployZimletRemotely(ZimletUtil.java:1238)
> at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1877)
> at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)
> com.zimbra.common.service.ServiceException: invalid request: server zldap.mydomain.tld does not have zimbraMailMode set, maybe it is not a store server?
> ExceptionId:main:1474372108997:83a53ef484c68f16
> Code:service.INVALID_REQUEST
> at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:267)
> at com.zimbra.cs.httpclient.URLUtil.getServiceURL(URLUtil.java:186)
> at com.zimbra.cs.util.WebClientServiceUtil.sendDeployZimletRequestToUiNode(WebClientServiceUtil.java:260)
> at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletOnUiNode(ZimletUtil.java:1567)
> at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletRemotely(ZimletUtil.java:1477)
> at com.zimbra.cs.zimlet.ZimletUtil.deployZimletRemotely(ZimletUtil.java:1238)
> at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1877)
> at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)
> [] ERROR: Error
> com.zimbra.common.service.ServiceException: invalid request: server zldap.mydomain.tld does not have zimbraMailMode set, maybe it is not a store server?
> ExceptionId:main:1474372108997:83a53ef484c68f16
> Code:service.INVALID_REQUEST
> at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:267)
> at com.zimbra.cs.httpclient.URLUtil.getServiceURL(URLUtil.java:186)
> at com.zimbra.cs.util.WebClientServiceUtil.sendDeployZimletRequestToUiNode(WebClientServiceUtil.java:260)
> at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletOnUiNode(ZimletUtil.java:1567)
> at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.deployZimletRemotely(ZimletUtil.java:1477)
> at com.zimbra.cs.zimlet.ZimletUtil.deployZimletRemotely(ZimletUtil.java:1238)
> at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1877)
> at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)

Maybe this is ok because zldap.mydomain.tld is indeed not a store server. Is it ok to ignore this error?

If i enable the zimlet for a user, he gets an error message at login:

> Server error (unknown command sent to server).
> method:   [unknown]
> msg:  unknown document: GetAvailableGroupsRequest
> code: service.UNKNOWN_DOCUMENT
> detail:   soap:Sender
> trace:    qtp509886383-198356:http://xxx.xxx.xxx.xxx:8080/service/soap/GetAvailableGroupsRequest:1474376904590:85b5566405fcb8da
> request:  
> <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">soap:Header<context xmlns="urn:zimbra"><userAgent name="ZimbraWebClient - GC52 (Linux)" version="8.6.0_GA_1194"/><session id="192869"/><account by="name">john.doe@mydomain.tld</account><format type="js"/></context>/soap:Headersoap:Body<GetAvailableGroupsRequest xmlns="urn:groupCal"/>/soap:Body/soap:Envelope

Launching groupcal.py also returns an error:
python /usr/local/bin/groupcal.py -D /opt/zimbra/data/caching.db zstore1.mydomain.tld admin@mydomain.tld "myadminpassword"

> Traceback (most recent call last):
>   File "/usr/local/bin/groupcal.py", line 178, in <module>
>     lists = search_response.get_response()["SearchDirectoryResponse"]["dl"]
> KeyError: 'dl'

**Comment by ghost** [comment]
Looks like, this needs to be installed on a store server, but I havent tested,

@Deelight-fr: Can you try and install it on a store server?

**Comment by Deelight-fr** [comment]
That was on a store server...

**Comment by dploeger** [comment]
Did you install the server extension on all store servers? The errors you mentioned look like it was not installed and Zimbra can't access the custom SOAP methods provided by the server extension.

**Comment by Deelight-fr** [comment]
You're right, the extension wasn't installed on all stores. Thanks.

However, I still have a problem running groupcal.py.

```
python /usr/local/bin/groupcal.py -d -D /opt/zimbra/data/caching.db zstore1.mydomain.tld admin@mydomain.tld 'mypassword'
DEBUG:root:Starting groupcal agent
DEBUG:root:Found list gcal_test@mydomain.tld
DEBUG:root:Working on account john.doe@mydomain.tld
DEBUG:root:Fetching preauth key for domain mydomain.tld
Traceback (most recent call last):
  File "/usr/local/bin/groupcal.py", line 360, in <module>
    preauth_cache[domain_part]
  File "/usr/local/lib/python2.7/dist-packages/pythonzimbra/tools/auth.py", line 104, in authenticate
    server.send_request(auth_request, response)
  File "/usr/local/lib/python2.7/dist-packages/pythonzimbra/communication.py", line 125, in send_request
    self.timeout
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/pythonzimbra/tools/urllib2_tls.py", line 43, in https_open
    return self.do_open(TLS1Connection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```

Authentication is OK because it finds a distribution list I created (gcal_test@mydomain.tld). Also, if i give a wrong admin password, I only get:

> DEBUG:root:Starting groupcal agent
> ERROR:root:Cannot login into zimbra with the supplied credentials.

It seems that groupcal.py is trying to login to connect to https://zstore1.mydomain.tld

**Comment by dploeger** [comment]
I think, you left out the actual error in your posting. 😀

Could you please paste the lines below "urllib2.URLError:"?

I'm guessing, the agent can not connect to your server due to SSL issues. Maybe you're using a self signed certificate or the hostname doesn't match the certificate.

**Comment by Deelight-fr** [comment]
Sorry, the "quote" formatting truncated the ouput. I edited my post.

I guess it can't connect because there's no 443 port open on the stores.

**Comment by dploeger** [comment]
Yes. That should be open. :)

**Comment by Deelight-fr** [comment]
Ok, I managed to make the script work by pointing the user_url variable to my Zimbra Proxy.
user_url = "https://proxy.domain.tld/service/soap"

Thanks!
