### ISSUE TITLE
appointments 

### ISSUE THREAD

**Issue by cribeironascimento** [dploeger/zimbra.de_dieploegers_groupcal#5]
I'm trying to install groupcal on Zimbra 8.6.0

I created distribution list gcal_teste@domain.tld and sec_gcal_teste@domain.tld

I run the command
#python /usr/local/bin/groupcal.py -d -D /opt/zimbra/data/caching.db email2.domain.tld admin@domain.tld 'password'

DEBUG:root:Starting groupcal agent
DEBUG:root:Found list gcal_tre@domain.tld 
DEBUG:root:Working on account manager@domain.tld 
DEBUG:root:Fetching preauth key for domain tre-pi.jus.br
DEBUG:root:Loading appointment TRE-PI: Visita Institucional Vmware
DEBUG:root:Adding appointment into database
DEBUG:root:Working on account maycon.teste@domain.tld 
DEBUG:root:No appointments found. Skipping
DEBUG:root:Working on account maycon.torres@domain.tld 
DEBUG:root:No appointments found. Skipping
DEBUG:root:Working on account teste2@domain.tld 
DEBUG:root:No appointments found. Skipping
DEBUG:root:Working on account teste3@domain.tld 
DEBUG:root:No appointments found. Skipping
DEBUG:root:Working on account teste4@domain.tld 
DEBUG:root:No appointments found. Skipping
DEBUG:root:Working on account teste@domain.tld 
DEBUG:root:Loading appointment teste
DEBUG:root:Adding appointment into database
DEBUG:root:Finished

However, the appointments don't showed on manager account. Why?

**Comment by dploeger** [comment]
So the manager@domain.tld is in the group sec_gcal_teste@domain.tld and uses the Group Cal zimlet view and doesn't see his own event "Visita Institucional Vmware"?

The way this extension works is by collecting events of the gcal_*-groups into a caching database, uses a server extension to fetch data from this database and display it in a zimlet view. Are you aware of that?
