### ISSUE TITLE
Support MariaDB (instead of or along with sqlite)

### ISSUE THREAD

**Issue by ghost** [dploeger/zimbra.de_dieploegers_groupcal#9]
I am not sure what the largest install base is/was for this Zimlet, but I expect some scalability issues using sqlite. (eg locked database when one process is using it)

**Comment by ghost** [comment]
@dploeger do you have any idea how much work this would be, and if it would be more or less work to just support only mariadb?

Did you have any scalability issues with sqlite?

**Comment by dploeger** [comment]
It would require reimplementing the agent with a database abstraction layer, so the customer could choose the target database, but no, there's no specific SQlite code inside.

I actually *had* that locking error, but it wasn't a scalability issue. I can't get my head around, what it was, though. If I remember, I'll let you known.

**Comment by dploeger** [comment]
SQlite actually supports concurrency: https://sqlite.org/faq.html#q5

And the only one writing to the database should be the agent.

**Comment by ghost** [comment]
fixed by replacing sqlite with mariadb
